server:
  port: '9000'

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/activityTracker
    password: '@Gurudesigner1'
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: update
welcome:
  message: Welcome to CodeWithDevlon!!
